### ISSUE TITLE
Automatización de máquinas

### ISSUE THREAD

**Issue by noviBB** [goscommons/Git_Intro_Automatica_Cujae#3]
Tesis de Lázaro
Modernización de fresas.
Motivación
En la cujae existen varias fresas, y todas funcionan de forma manual. La idea de este proyecto es automatizar el funcionamiento de estas fresadoras.

**Comment by rtritzant** [comment]
link:  http://www.gnccaldereria.es/tipos-fresadoras-existen/
1.Tipos de fresadoras según la orientación de la herramienta o del eje de giro
1.1 Tipos de fresadoras verticales
Y en este tipo de fresadoras verticales podemos encontrar dos tipos:

1.1.1 Fresadoras verticales de bancada o de banco fijo

1.1.2 Fresadoras verticales de consola o de torreta

1.2 Tipos de fresadoras horizontales

1.3 Tipos de fresadoras universales

**Comment by yelenamd** [comment]
Para conocer como funciona una fresadora y los tipos que existen, en este link se encuentra informacion:
http://biblio3.url.edu.gt/Libros/2013/pro_ma/11.pdf

**Comment by jlvichotp** [comment]
Objetivos Específicos:

-Realizar análisis del estado del arte de las fresadoras.
-Realizar un análisis técnico del estado actual de la fresa a modernizar.
-Diseñar los componentes mecanicos a reemplazar.
-Modelado Matematemático de la fresadora
-Diseño del Hardware para el control automatizado de la fresadora
-Diseño de la interfaz gráfica para importar archivos CAD

**Comment by dayronolmo** [comment]
Encontré una tesis donde podemos tener una idea de como automatizar una fresadora en este caso la tesis es para utilizarla con control numerico el link es el siguiente:
http://bibdigital.epn.edu.ec/handle/15000/1572

**Comment by noviBB** [comment]
los objetivos deben estar en infinitivo

**Comment by yelenamd** [comment]
En este link, se encuentra una tesis sobre  el estudio de factibilidad para la automatización de un torno y automatización de una fresadora.
https://repositoriotec.tec.ac.cr/bitstream/handle/2238/5635/estudio%20factibilidad%20automatizacion%20torno%20fresadora.pdf?sequence=1&isAllowed=y

**Comment by Dps8** [comment]
Agregar a objetivos específicos:
Algoritmos de control de posicionamiento para una fresadora
